version: "3.9"

services:
  db:
    image: mysql:8.1
    container_name: crypto_notifier_db_dev
    env_file:
      - .env.dev
    ports:
      - "3307:3306" # expose DB to host for local app connection
    volumes:
      - mysql_data_dev:/var/lib/mysql

volumes:
  mysql_data_dev:
